export const CourseActionTypes = {
    ENROLLED_REQUEST: '@@courses/ENROLLED_REQUEST',
    ENROLLED_SUCCESS: '@@courses/ENROLLED_SUCCESS',
    ENROLLED_FAILURE: '@@courses/ENROLLED_FAILURE',

    NOTENROLLED_REQUEST: '@@courses/NOTENROLLED_REQUEST',
    NOTENROLLED_SUCCESS: '@@courses/NOTENROLLED_SUCCESS',
    NOTENROLLED_FAILURE: '@@courses/NOTENROLLED_FAILURE',

    ENROLL_REQUEST: '@@courses/ENROLL_REQUEST',
    ENROLL_SUCCESS: '@@courses/ENROLL_SUCCESS',
    ENROLL_FAILURE: '@@courses/ENROLL_FAILURE',

    SECTION_REQUEST: '@@courses/SECTION_REQUEST',
    SECTION_SUCCESS: '@@courses/SECTION_SUCCESS',
    SECTION_FAILURE: '@@courses/SECTION_FAILURE',

    MARKDONE_REQUEST: '@@courses/MARKDONE_REQUEST',
    MARKDONE_SUCCESS: '@@courses/MARKDONE_SUCCESS',
    MARKDONE_FAILURE: '@@courses/MARKDONE_FAILURE',
};
